import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./Footer/page";
import Navebar from "./Navbar/page";
// import TopButton from "./top/page"; // Corrected import

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "INFINITY GOLDEN JEWELRY",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navebar /> {/* Corrected component name */}
        {children} <Footer />
        {/* <TopButton /> */}
      </body>
    </html>
  );
}
